---
jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          role-session-name: OIDCSession
          role-to-assume: arn:aws:iam::008971671688:role/AWSRoleForGithub
      - run: aws s3 ls
        shell: bash
name: AWS Testing
'on':
  workflow_dispatch: null
permissions:
  id-token: write