name: 'AWS Testing'

on:
  workflow_dispatch:
    
permissions:
  id-token: write 

jobs: 
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::008971671688:role/AWSRoleForGithub
          role-session-name: OIDCSession
        
      - run: aws s3 ls
        shell: bash